/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.fontbox.ttf;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

import org.apache.pdfbox.io.RandomAccessReadBuffer;
import org.junit.jupiter.api.Test;

/**
 * Golden test comparing the FontBox interpreter's grid-fitted glyph points against a FreeType
 * reference dump (same font, glyph and ppem). The reference lives in {@code ttf/hinting/<font>-<ppem>.txt},
 * produced offline by {@code generate_golden.py}; FreeType is never a build or runtime dependency.
 * <p>
 * The reference is generated by FreeType 2.13.2 with the <b>grayscale</b> target
 * ({@code FT_LOAD_TARGET_NORMAL}), i.e. the v40 "minimal" subpixel interpreter with backward
 * compatibility, because PDFBox always rasterizes antialiased (Java2D). The interpreter reproduces it
 * exactly: every x and y coordinate of every glyph matches. Coordinates are integer F26Dot6 (64 units
 * per pixel), so any difference at all - even 1/64 px - fails, and the message names the worst point.
 * (Beyond this bundled font, {@code HintedPointsDumpTool} with {@code compare_points.py} checks the
 * same against any local fonts.)
 */
class GoldenHintingTest
{
    private static final int[] PPEMS = { 11, 13, 16, 24 };

    @Test
    void testSimpleGlyphsMatchFreeTypeExactly() throws IOException
    {
        Stats simple = compare(false);
        assertTrue(simple.compared > 0, simple.summary("simple"));
        assertTrue(simple.maxDx == 0 && simple.maxDy == 0, simple.summary("simple"));
    }

    /**
     * Every golden composite carries instructions of its own (checked in {@link #compare}), so this
     * covers the whole composite path: components hinted and assembled, then the composite program.
     */
    @Test
    void testCompositeGlyphsMatchFreeTypeExactly() throws IOException
    {
        Stats composite = compare(true);
        assertTrue(composite.compared > 0, composite.summary("composite"));
        assertTrue(composite.maxDx == 0 && composite.maxDy == 0, composite.summary("composite"));
    }

    private Stats compare(boolean composite) throws IOException
    {
        TrueTypeFont font;
        try (InputStream is = getClass().getResourceAsStream("/ttf/LiberationSans-Regular.ttf"))
        {
            font = new TTFParser().parse(new RandomAccessReadBuffer(is));
        }
        GlyphHinter hinter = new GlyphHinter(font);
        Stats s = new Stats();

        for (int ppem : PPEMS)
        {
            List<GoldenGlyph> golden = loadGolden("/ttf/hinting/LiberationSans-Regular-" + ppem + ".txt");
            assertNotNull(golden);
            for (GoldenGlyph g : golden)
            {
                boolean isComposite = font.getGlyph().getGlyph(g.gid).getNumberOfContours() < 0;
                if (isComposite != composite)
                {
                    continue;
                }
                if (composite)
                {
                    // the composite's own program must run, not just its components' programs, so
                    // an exact match proves the composite path rather than only the component one
                    GlyfCompositeDescript cd = (GlyfCompositeDescript) font.getGlyph()
                            .getGlyph(g.gid).getDescription();
                    int[] instructions = cd.getInstructions();
                    assertTrue(instructions != null && instructions.length > 0,
                            "golden composite '" + g.ch + "' has no instructions of its own");
                }
                // null would mean the hinter gave up and the raw outline would be rendered
                int[][] points = hinter.getHintedPointsF26Dot6(g.gid, ppem);
                assertNotNull(points, "no hinted points for gid " + g.gid + " at " + ppem + "ppem");
                assertTrue(points[0].length == g.x.length,
                        "point count mismatch for '" + g.ch + "' at " + ppem + "ppem: ours="
                                + points[0].length + " freetype=" + g.x.length);
                s.recordGlyph(g, ppem, points);
            }
        }
        return s;
    }

    private static final class Stats
    {
        private int compared;
        private int maxDx;
        private int maxDy;
        private int worst;
        private String worstWhere = "none";

        void recordGlyph(GoldenGlyph g, int ppem, int[][] points)
        {
            for (int i = 0; i < g.x.length; i++)
            {
                compared++;
                int dx = Math.abs(points[0][i] - g.x[i]);
                int dy = Math.abs(points[1][i] - g.y[i]);
                maxDx = Math.max(maxDx, dx);
                maxDy = Math.max(maxDy, dy);
                if (Math.max(dx, dy) > worst)
                {
                    worst = Math.max(dx, dy);
                    worstWhere = "'" + g.ch + "' (gid " + g.gid + ") point " + i + " @" + ppem
                            + "ppem: ours=(" + points[0][i] + "," + points[1][i] + ") freetype=("
                            + g.x[i] + "," + g.y[i] + ")";
                }
            }
        }

        String summary(String kind)
        {
            return kind + ": compared " + compared + " coords; maxDx=" + maxDx + "/64 maxDy=" + maxDy
                    + "/64; worst at " + worstWhere;
        }
    }

    private List<GoldenGlyph> loadGolden(String resource) throws IOException
    {
        List<GoldenGlyph> glyphs = new ArrayList<>();
        try (InputStream is = getClass().getResourceAsStream(resource);
                BufferedReader reader = new BufferedReader(
                        new InputStreamReader(is, StandardCharsets.UTF_8)))
        {
            GoldenGlyph current = null;
            String line;
            while ((line = reader.readLine()) != null)
            {
                if (line.startsWith("glyph "))
                {
                    String[] parts = line.split(" ");
                    current = new GoldenGlyph(Integer.parseInt(parts[1]), parts[2]);
                    glyphs.add(current);
                }
                else if (line.startsWith("x "))
                {
                    current.x = parseInts(line.substring(2));
                }
                else if (line.startsWith("y "))
                {
                    current.y = parseInts(line.substring(2));
                }
            }
        }
        return glyphs;
    }

    private static int[] parseInts(String s)
    {
        if (s.isEmpty())
        {
            return new int[0];
        }
        String[] tokens = s.split(" ");
        int[] values = new int[tokens.length];
        for (int i = 0; i < tokens.length; i++)
        {
            values[i] = Integer.parseInt(tokens[i]);
        }
        return values;
    }

    private static final class GoldenGlyph
    {
        private final int gid;
        private final String ch;
        private int[] x;
        private int[] y;

        GoldenGlyph(int gid, String ch)
        {
            this.gid = gid;
            this.ch = ch;
        }
    }
}
