name: Sonarcloud analyze

on: [push]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    environment: sonarcloud
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: clean
      run: mvn clean
    - name: SonarCloud
      run: mvn -B verify sonar:sonar -Dsonar.projectKey=habbisify_pdfbox -Dsonar.organization=habbisify -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} -DskipTests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
